# Generated by Django 5.0.6 on 2025-09-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_band', models.CharField(blank=True, max_length=100)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.CharField(blank=True, max_length=100)),
                ('issue_type', models.CharField(blank=True, max_length=100)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('listed', 'Listed')], default='upcoming', max_length=20)),
                ('ipo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rhp_pdf', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('drhp_pdf', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='api.company')),
            ],
            options={
                'ordering': ['-open_date'],
            },
        ),
    ]
